[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./server/deployments" }]

auto_detect_remappings = false
remappings = [
    "@phlimbo-ea/=lib/phlimbo-ea/src/",
    "@phUSD-stable-minter/=lib/phUSD-stable-minter/src/",
    "@stable-yield-accumulator/=lib/stable-yield-accumulator/src/",
    "@openzeppelin/contracts/=lib/phUSD-stable-minter/lib/openzeppelin-contracts/contracts/",
    "@forge-std/=lib/forge-std/src/",
    "@vault-interfaces/=lib/vault/src/interfaces/",
    "@vault/=lib/vault/src/",
    "@pauser/=lib/pauser/src/",
    "pauser/=lib/pauser/src/",
    "forge-std/=lib/forge-std/src/",
    "lib/mutable/pauser/=lib/pauser/",
    "vault/interfaces/=lib/vault/src/interfaces/",
    "phlimbo-ea/=lib/phlimbo-ea/src/",
    "lib/phUSD-stable-minter/lib/mutable/pauser/=lib/pauser/",
    "lib/stable-yield-accumulator/lib/mutable/pauser/=lib/pauser/",
    "lib/phlimbo-ea/lib/mutable/pauser/=lib/pauser/",
    "lib/phUSD-stable-minter/lib/mutable/vault/=lib/vault/",
    "openzeppelin-contracts/=lib/phUSD-stable-minter/lib/openzeppelin-contracts/",
    "erc4626-tests/=lib/phUSD-stable-minter/lib/openzeppelin-contracts/lib/erc4626-tests/",
    "halmos-cheatcodes/=lib/phUSD-stable-minter/lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
    "v4-core/=lib/stable-yield-accumulator/lib/v4-periphery/lib/v4-core/src/",
    "v4-periphery/=lib/stable-yield-accumulator/lib/v4-periphery/",
    "@uniswap/v4-core/=lib/stable-yield-accumulator/lib/v4-periphery/lib/v4-core/",
    "lib/stable-yield-accumulator/lib/openzeppelin-contracts/=lib/stable-yield-accumulator/lib/openzeppelin-contracts/",
    "@flax-token/=lib/flax-token-v2/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[lint]
lint_on_build = false
