[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./server/deployments" }]

remappings = [
    "@phlimbo-ea/=lib/phlimbo-ea/src/",
    "@phUSD-stable-minter/=lib/phUSD-stable-minter/src/",
    "@stable-yield-accumulator/=lib/stable-yield-accumulator/src/",
    "@openzeppelin/contracts/=lib/phUSD-stable-minter/lib/openzeppelin-contracts/contracts/",
    "@forge-std/=lib/forge-std/src/",
    "@vault-interfaces/=lib/phUSD-stable-minter/lib/mutable/vault/src/interfaces/",
    "pauser/=lib/stable-yield-accumulator/lib/mutable/pauser/src/",
    "vault/interfaces/=lib/phUSD-stable-minter/lib/mutable/vault/src/interfaces/",
    "phlimbo-ea/=lib/phlimbo-ea/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
